version: 2

build:
  os: ubuntu-22.04
  apt_packages:
    - librsvg2-bin
  tools:
    python: "3.11"

python:
  version: 3.11

sphinx:
   configuration: source/conf.py

python:
   install:
   - requirements: requirements.txt

formats:
   - pdf
   - epub
