# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

import os.path
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '_ext'))

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#sys.path.insert(0, os.path.abspath('.'))

# -- General configuration -----------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be extensions
# coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.viewcode',
    'sphinx.ext.doctest',
    'edit_on_github',
    'sphinxcontrib.rsvgconverter'
]

edit_on_github_project = 'wtuemura/mamedoc'
edit_on_github_branch = 'master/source'

# Math
# mathjax_path = "http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# Define a codificação padrão do texto
source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
#project = u'Manual de Instruções do MAME'
#copyright = u'2018, Equipe de Desenvolvimento do MAME, MAMEdev'
project = u'Documentação'
copyright = u'2024, Equipe de Desenvolvimento do MAME (MAMEdev), Tradução e Revisão Wellington T. Uemura'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = 'MAME 0.270'
# The full version, including alpha/beta/rc tags.
release = '0.270'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = 'pt_BR'
default_lang = "pt_BR"
project_language = 'pt_BR'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'tango'

# -- Options for HTML output ---------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {
    # 'sticky_navigation': True  # Set to False to disable the sticky nav while scrolling.
    # 'logo_only': True,  # if we have a html_logo below, this shows /only/ the logo with no title text
}

# Add any paths that contain custom themes here, relative to this directory.
#html_theme_path = ["../themes/"]

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
#html_title = None

# A shorter title for the navigation bar.  Default is the same as html_title.
#html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = "images/mame-logo.png"

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = "images/favicon.ico"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['static']
html_css_files = ['css/custom.css']

#html_context = {
#    'css_files': [
#    '_static/css/theme_overrides.css',  # override wide tables in RTD theme
#    ],
#}
#html_theme_path = ["../themes/"]

# https://github.com/readthedocs/sphinx_rtd_theme/issues/714
# getting error when try to load custom css
#def setup(app):
#    app.add_css_file( "custom.css")

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
#html_last_updated_fmt = '%b %d, %Y'

# We don't want smartquotes in general.
smartquotes = False

# If true, links to the reST sources are added to the pages.
html_show_sourcelink = False

# Output file base name for HTML help builder.
htmlhelp_basename = 'MAME'

# Mostrar "Compilado com Sphinx"
#html_show_sphinx = False
#html_show_sourcelink = False

# -- Options for LaTeX output --------------------------------------------------

latex_engine = 'pdflatex'

latex_elements = {
# Construa o nosso documento na língua Portuguesa (Português Brasileiro)
'babel': r'\usepackage[brazil]{babel}',

# The paper size ('letterpaper' or 'a4paper').
#'papersize': 'letterpaper',
# The font size ('10pt', '11pt' or '12pt').
'pointsize': '10pt',

# Additional stuff for the LaTeX preamble.
#
# Em ordem
# charter = serif font
# lato = sans-serif font
# inconsolata = monospace font
#
# Source: https://protips.readthedocs.io/pdf-font.html
#'preamble': '''

'preamble': r'''
\usepackage{charter}
\usepackage[defaultsans]{lato}
\usepackage{inconsolata}
''',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass [howto/manual]).
latex_documents = [
  ('index', 'MAME-pt_BR.tex', 'Documentação - MAME',
   'Tradução e Revisão Wellington T. Uemura', 'manual')
]


# -- Options for manual page output --------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    ('index', 'MAME', u'',
     [u'Equipe de Desenvolvimento do MAME, MAMEdev \\Tradução e Revisão Wellington T. Uemura'], 1)
]


# -- Options for Texinfo output ------------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
  ('index', 'MAME-pt_BR', u'Documentação - MAME',
   u'Equipe de Desenvolvimento do MAME, MAMEdev \\Tradução e Revisão Wellington T. Uemura \\Português do Brasil', 'MAME', 'Multi-purpose emulation framework',
   'Emulation'),
]

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#texinfo_show_urls = 'footnote'
# Suppress "WARNING: unknown mimetype for ..." https://github.com/IQSS/dataverse/issues/3391
suppress_warnings = ['epub.unknown_project_files']

# -- Options for Epub ----------------------------------------------------------

epub_theme = 'epub'
epub_basename = 'mamedoc'
epub_author = 'Wellington Terumi Uemura'
epub_publisher = 'https://mamedoc.readthedocs.io/'
epub_uid = 'web-site'
epub_scheme = 'url'
epub_identifier = epub_publisher
epub_fix_images = False
epub_max_image_width = 0
epub_show_urls = 'inline'
epub_use_index = False
epub_version = 0.270
